// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        AButton: typeof import('ant-design-vue/es')['Button']
        ButtonCounter: typeof import('./src/components/buttonCounter.vue')['default']
        ButtonWrapper: typeof import('./src/components/buttonWrapper.vue')['default']
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
        IMdiAccount: typeof import('~icons/mdi/account')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        RouterViewTransition: typeof import('./src/components/RouterViewTransition.vue')['default']
    }
}

export {}
